package:
  name: bibtools
  version: "0.1"

source:
  fn: bibtools-0.1.tar.gz
  url: https://pypi.python.org/packages/source/b/bibtools/bibtools-0.1.tar.gz
  md5: xxxx

build:
  entry_points:
    - bib = bibtools.cli:commandline
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python

about:
  home: https://github.com/pkgw/bibtools/
  license: MIT License
  summary: A command-line bibliography manager.
