package:
  name: bibtools
  version: "0.2"

source:
  fn: bibtools-0.2.tar.gz
  url: https://pypi.python.org/packages/source/b/bibtools/bibtools-0.2.tar.gz
  md5: d19809dbc1e9b78bf621cf88ead1e95a

build:
  entry_points:
    - bib = bibtools.cli:commandline
  number: 0

requirements:
  build:
    - pwkit
    - python
    - setuptools

  run:
    - pwkit
    - python

about:
  home: https://github.com/pkgw/bibtools/
  license: MIT License
  summary: A command-line bibliography manager.
